'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class index
    
    '''<summary>
    '''header_helpIcon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents header_helpIcon As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''InvalidCredLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents InvalidCredLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''login_usernameTB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents login_usernameTB As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''login_passwordTB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents login_passwordTB As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''login_submitButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents login_submitButton As Global.System.Web.UI.WebControls.ImageButton
End Class
