'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class pos
    
    '''<summary>
    '''SqlDataSource1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource1 As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''addBar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents addBar As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''addIcon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents addIcon As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''searchBar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents searchBar As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''searchIcon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents searchIcon As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''searchResults control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents searchResults As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''pos_editIcon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pos_editIcon As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''pos_voidIcon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pos_voidIcon As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''poshelpIcon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents poshelpIcon As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''posMultiView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents posMultiView As Global.System.Web.UI.WebControls.MultiView
    
    '''<summary>
    '''purchaseView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents purchaseView As Global.System.Web.UI.WebControls.View
    
    '''<summary>
    '''purchaseBannerPurchase control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents purchaseBannerPurchase As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''purchaseList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents purchaseList As Global.System.Web.UI.WebControls.ListBox
    
    '''<summary>
    '''purchasePriceLB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents purchasePriceLB As Global.System.Web.UI.WebControls.ListBox
    
    '''<summary>
    '''DeleteButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DeleteButton As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''returnBannerPurchase control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents returnBannerPurchase As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''paymentBannerPurchase control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents paymentBannerPurchase As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''returnView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents returnView As Global.System.Web.UI.WebControls.View
    
    '''<summary>
    '''purchaseBannerReturn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents purchaseBannerReturn As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''returnBannerReturn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents returnBannerReturn As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''returnList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents returnList As Global.System.Web.UI.WebControls.ListBox
    
    '''<summary>
    '''returnPriceLB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents returnPriceLB As Global.System.Web.UI.WebControls.ListBox
    
    '''<summary>
    '''DeleteRButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DeleteRButton As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''paymentBannerReturn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents paymentBannerReturn As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''paymentView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents paymentView As Global.System.Web.UI.WebControls.View
    
    '''<summary>
    '''purchaseBannerPayment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents purchaseBannerPayment As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''returnBannerPayment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents returnBannerPayment As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''paymentBannerPayment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents paymentBannerPayment As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''cashButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cashButton As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''cardButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cardButton As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''paymentInputContainer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents paymentInputContainer As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''paymentTB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents paymentTB As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''submit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents submit As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''employeeDisplay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents employeeDisplay As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''dateDisplay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dateDisplay As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''timeDisplay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents timeDisplay As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''purchaseTotal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents purchaseTotal As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''returnTB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents returnTB As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''returnTotal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents returnTotal As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''subTotalTB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents subTotalTB As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''subTotal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents subTotal As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''taxTB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents taxTB As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''tax control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tax As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''totalTB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents totalTB As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''total control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents total As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''checkoutButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents checkoutButton As Global.System.Web.UI.WebControls.ImageButton
End Class
