'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class pos
    
    '''<summary>
    '''addBar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents addBar As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''addIcon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents addIcon As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''pos_editIcon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pos_editIcon As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''pos_voidIcon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pos_voidIcon As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''poshelpIcon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents poshelpIcon As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''posMultiView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents posMultiView As Global.System.Web.UI.WebControls.MultiView
    
    '''<summary>
    '''purchaseView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents purchaseView As Global.System.Web.UI.WebControls.View
    
    '''<summary>
    '''purchaseBannerPurchase control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents purchaseBannerPurchase As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''CategoriesDD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CategoriesDD As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ProductsDD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ProductsDD As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''SqlDataSource1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource1 As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''ProductDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ProductDetails As Global.System.Web.UI.WebControls.DetailsView
    
    '''<summary>
    '''returnBannerPurchase control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents returnBannerPurchase As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''paymentBannerPurchase control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents paymentBannerPurchase As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''returnView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents returnView As Global.System.Web.UI.WebControls.View
    
    '''<summary>
    '''purchaseBannerReturn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents purchaseBannerReturn As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''returnBannerReturn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents returnBannerReturn As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''paymentBannerReturn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents paymentBannerReturn As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''paymentView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents paymentView As Global.System.Web.UI.WebControls.View
    
    '''<summary>
    '''purchaseBannerPayment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents purchaseBannerPayment As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''returnBannerPayment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents returnBannerPayment As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''paymentBannerPayment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents paymentBannerPayment As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''checkoutButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents checkoutButton As Global.System.Web.UI.WebControls.ImageButton
End Class
