'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class pos
    
    '''<summary>
    '''posMultiView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents posMultiView As Global.System.Web.UI.WebControls.MultiView
    
    '''<summary>
    '''purchaseView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents purchaseView As Global.System.Web.UI.WebControls.View
    
    '''<summary>
    '''purchaseBannerPurchase control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents purchaseBannerPurchase As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''returnBannerPurchase control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents returnBannerPurchase As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''paymentBannerPurchase control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents paymentBannerPurchase As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''returnView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents returnView As Global.System.Web.UI.WebControls.View
    
    '''<summary>
    '''purchaseBannerReturn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents purchaseBannerReturn As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''returnBannerReturn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents returnBannerReturn As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''paymentBannerReturn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents paymentBannerReturn As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''paymentView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents paymentView As Global.System.Web.UI.WebControls.View
    
    '''<summary>
    '''purchaseBannerPayment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents purchaseBannerPayment As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''returnBannerPayment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents returnBannerPayment As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''paymentBannerPayment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents paymentBannerPayment As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''checkoutButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents checkoutButton As Global.System.Web.UI.WebControls.ImageButton
End Class
