'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class reports
    
    '''<summary>
    '''homeIcon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents homeIcon As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''printIcon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents printIcon As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''poshelpIcon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents poshelpIcon As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''reportsMultiView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reportsMultiView As Global.System.Web.UI.WebControls.MultiView
    
    '''<summary>
    '''summaryView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents summaryView As Global.System.Web.UI.WebControls.View
    
    '''<summary>
    '''netSalesHourlyTB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents netSalesHourlyTB As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''avgHourlyTB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents avgHourlyTB As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''unitsPerHourlyTB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents unitsPerHourlyTB As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''numTransHourlyTB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents numTransHourlyTB As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''netSalesDailyTB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents netSalesDailyTB As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''avgDailyTB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents avgDailyTB As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''unitsPerDailyTB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents unitsPerDailyTB As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''numTransDailyTB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents numTransDailyTB As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''detailedView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents detailedView As Global.System.Web.UI.WebControls.View
    
    '''<summary>
    '''DetailedReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DetailedReport As Global.System.Web.UI.WebControls.DetailsView
    
    '''<summary>
    '''timeDisplay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents timeDisplay As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''dateDisplay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dateDisplay As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''detailedButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents detailedButton As Global.System.Web.UI.WebControls.ImageButton
End Class
