'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class reports
    
    '''<summary>
    '''calenderStartDD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents calenderStartDD As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''calenderEndDD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents calenderEndDD As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''locationDD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents locationDD As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''homeIcon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents homeIcon As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''printIcon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents printIcon As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''poshelpIcon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents poshelpIcon As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''reportsMultiView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reportsMultiView As Global.System.Web.UI.WebControls.MultiView
    
    '''<summary>
    '''summaryView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents summaryView As Global.System.Web.UI.WebControls.View
    
    '''<summary>
    '''detailedView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents detailedView As Global.System.Web.UI.WebControls.View
    
    '''<summary>
    '''detailedButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents detailedButton As Global.System.Web.UI.WebControls.ImageButton
End Class
